FROM pytorch/pytorch

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3-pip \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY docker/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./docker/jupyter_start.sh /usr/local/bin/jupyter_start.sh
RUN chmod +x /usr/local/bin/jupyter_start.sh

EXPOSE 8888 5000

CMD ["jupyter_start.sh"]
