name: GOGO-AI-PROFANITY-FILTER stage CD

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.STAGE_SSH_HOST }}
          port: ${{ secrets.STAGE_SSH_PORT }}
          username: ${{ secrets.STAGE_SSH_USERNAME }}
          password: ${{ secrets.STAGE_SSH_PASSWORD }}
          script: |
            set -e

            mkdir -p /home/ubuntu/gogo-profanity-filter
            cd /home/ubuntu/gogo-profanity-filter

            if [ ! -d ".git" ]; then
              git clone -b master https://github.com/team-gogo/gogo-ai .
            else
              git pull origin master
            fi

            docker build . -t gogo-profanity-filter-stage

            docker stop gogo-profanity-filter-stage || true
            docker rm gogo-profanity-filter-stage || true

            docker run -d -p 8087:8087 --add-host host.docker.internal:host-gateway --name gogo-profanity-filter-stage gogo-profanity-filter-stage

      - name: SSH Success Notification
        if: success()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          color: 0x4CAF50
          title: "STAGE 배포 성공"
          message: "GOGO Profanity Filter stage deployment completed successfully."

      - name: SSH Failure Notification
        if: failure()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          color: 0xFF4C4C
          title: "STAGE 배포 실패"
          message: "GOGO Profanity Filter stage deployment failed. Check the logs for details."
